parameters:
  - name: projectName
    type: string
    default: ""

steps:
  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: "16.x"

  - script: |
      npm i -g typescript
      npm ci
    displayName: "Install Dependencies"

  - script: |
      npm run build
    displayName: "Build App"

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Build Artifacts'
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)'
      artifactName: ${{ parameters.projectName }}
